const artists = [
  "Tyler The Creator",
  "The Killers",
  "Sturgill Simpson",
  "The Postal Service",
  "Grace Jones",
  "Kaytranada",
  "Jungle",
  "Chris Lake",
  "Gryffin",
  "Snoh Aalegra",
  "Young The Giant",
  "Schoolboy Q",
  "Teddy Swims",
  "Renee Rapp",
  "Victoria Monet",
  "Knock2",
  "Slowdive",
  "Killer Mike",
  "Fletcher",
  "TV Girl",
  "Tyla",
  "Chappell Roan",
  "Channel Tres",
  "Charley Crockett",
  "Men I Trust",
  "Ben Howard",
  "Amyl and The Sniffers",
  "Kevin Abstract",
  "Paul Cauthen",
  "The Japanese House",
  "Romy",
  "The Last Dinner Party",
  "Babe Rainbow",
  "STRFKR",
  "Real Estate",
  "K.Flay",
  "Corinne Bailey Rae",
  "Snakehips",
  "Amen Dunes",
  "Roosevelt",
  "Alienboy",
  "Mindchatter",
  "Dadi Freyr",
  "Ryan Beatty",
  "Leisure",
  "Elyanna",
  "Confidence Man",
  "Kasablanca",
  "Vandelux",
  "WISP",
  "Medium Build",
  "Rocco",
  "Underscores",
  "Devault",
  "Chance Pena",
  "Mimi Webb",
  "Daily Bread",
  "Balthvs",
  "Shaboozey",
  "Billy Woods",
  "The Lemon Twigs",
  "Sons Of The East",
  "CMAT",
  "Cimafunk",
  "Katie Pruitt",
  "AG Club",
  "Lady Wray",
  "Odie Leigh",
  "French Cassettes",
  "A.G. Miles",
  "Valencia Grace",
  "Spencer",
  "Leal Neale",
  "SOMA",
  "Angrybaby",
  "Anish Kumar",
  "ARYBO",
  "The Blessed Madonna",
  "Buns",
  "Chuck Gunn",
  "Darius",
  "Dusky",
  "Nerve Now",
  "B2B Jade Thompson",
  "Idris Elba",
  "Jackie Hollander",
  "Joe Kay",
  "Jared Jackson",
  "Kaleena Zanders",
  "Seth Troxler",
  "Shiba San B2B CID",
  "Sidepiece",
  "Sofia Kourtesis",
  "Tsha",
  "Uncle Waffles",
  "Yulia Niko",
  "Post Malone",
];
