import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { SessionProvider } from "@/components/provider";
import { cn } from "@/lib/utils";
import "./globals.css";
import Header from "@/components/Header";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Festival Lineup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-[#22372B] text-white font-sans antialiased",
          fontSans.variable
        )}
      >
        <Header />
        <main className="flex-grow">
          <SessionProvider>{children}</SessionProvider>
        </main>
      </body>
    </html>
  );
}
