export const festivals = [
  {
    id: 1,
    name: "Life is Beautiful",
    src: "/assets/festivals/lib.jpg",
    artists: [
      "Justice",
      "Peggy Gou",
      "LCD Soundsystem",
      "Jamie XX",
      "Jungle",
      "James Blake",
      "Thundercat",
      "Toro y Moi",
      "Badbadnotgood",
      "Neil Frances",
      "LP Giobbi",
      "Empress Of",
      "John Talabot",
    ],
  },
  {
    id: 2,
    name: "Outside Lands",
    src: "/assets/festivals/osl.png",
    artists: [
      "Tyler, the Creator",
      "The Killers",
      "Sturgill Simpson",
      "The Postal Service",
      "Grace Jones",
      "Kaytranada",
      "Jungle",
      "Chris Lake",
      "Gryffin",
      "Snoh Aalegra",
      "Young the Giant",
      "Schoolboy Q",
      "Teddy Swims",
      "Reneé Rapp",
      "Victoria Monét",
      "Knock2",
      "Slowdive",
      "Killer Mike",
      "Fletcher",
      "TV Girl",
      "Tyla",
      "Chappell Roan",
      "Channel Tres",
      "Charley Crockett",
      "Men I Trust",
      "Ben Howard",
      "Amyl and the Sniffers",
      "Kevin Abstract",
      "Paul Cauthen",
      "The Japanese House",
      "Romy",
      "The Last Dinner Party",
      "Babaandtoogood",
      "STRFKR",
      "Real Estate",
      "K.Flay",
      "Corinne Bailey Rae",
      "Snakehips",
      "Amen Dunes",
      "Roosevelt",
      "Allen Stone",
      "Mindchatter",
      "Daði Freyr",
      "Ryan Beatty",
      "Leisure",
      "Elyanna",
      "Confidence Man",
      "Kasablanca",
      "Vandelux",
      "Wisp",
      "Medium Build",
      "Rocco",
      "Underscores",
      "Devault",
      "Chance Peña",
      "Mimi Webb",
      "Daily Bread",
      "Balthvs",
      "Shaboosie",
      "Billy Woods",
      "The Lemon Twigs",
      "Trueno",
      "Sons Of The East",
      "CMAT",
      "Cimafunk",
      "Katie Pruitt",
      "AG Club",
      "Lady Wray",
      "Odileigh",
      "French Cassettes",
      "Ogi",
      "Miles.",
      "Valencia Grace",
      "Dan Spencer",
      "Lael Neale",
      "Angrybaby",
      "Anish Kumar",
      "AYYBO",
      "Darius",
      "Dusky",
      "Honeyluv",
      "Jaden Thompson",
      "Idris Elba",
      "Jackie Hollander",
      "Joe Kay",
      "Jared Jackson",
      "Kaleena Zanders",
      "Marsh",
      "Seth Troxler",
      "Shiba San",
      "Sidepiece",
      "Sofia Kourtesis",
      "TSHA",
      "Uncle Waffles",
      "Yulia Niko",
      "Post Malone",
    ],
  },
  {
    id: 3,
    name: "Portola",
    src: "/assets/festivals/portola.jpg",
    artists: [
      "RÜFÜS DU SOL",
      "BICEP",
      "CHROMA",
      "GESEFFELSTEIN",
      "FLOATING POINTS",
      "FCUKERS",
      "EMPRESS OF",
      "NOORIYAH",
      "NEIL FRANCES",
      "FRANC MOODY",
      "SNOW STRIPPERS",
      "DELTRON 3030",
      "MALL GRAB",
      "JESSIE WARE",
      "NILS HOFFMANN",
      "INTERPLANETARY CRIMINAL",
      "PEACHES",
      "JOY ORBISON",
      "A. G. COOK",
      "FOUR TET",
      "SOULWAX",
      "JPEGMAFIA",
      "TYCHO",
      "LAVA LA RUE",
      "JAMIE XX",
      "ASTRA CLUB",
      "NIA ARCHIVES",
      "NAL",
      "LUKE ALESSI",
      "HONEY DIJON",
      "MOUNT KIMBIE",
      "FISHER",
      "RAF SPERA",
      "PRETTY GIRL",
      "DJ SEINFELD",
      "KENYA GRACE",
      "DJ STARRZA",
      "AHADADREAM",
      "SAMMY VIRJI",
      "JERSEY FISHER",
      "LP GIOBBI",
      "PANJABI HIT SQUAD",
      "DISCLOSURE",
      "BEN BÖHMER",
      "CHASE & STATUS",
      "SARA LANDRY",
      "M.I.A.",
      "DJ HEARTSTRING",
      "REBECCA BLACK",
      "SHYGIRL PRESENTS CLUB SHY",
      "GLASS BEAMS",
      "ANDERSON .PAAK",
      "HORSEGIRL",
      "BUSY P",
      "BRAXE + FALCON",
      "BARRY CAN'T SWIM",
      "JUSTICE",
      "BOYS NOIZE",
      "VTSS"
    ],
  },
];
